services:
  web1:
    build: 
      context: ./server
      no_cache: true
    hostname: web1
    ports:
      - '81:3000'
  nginx:
    build: ./nginx
    ports: 
      - '80:80'
    depends_on:
      - web1


